version: "3.5"
services:
  api:
    container_name: heimdallr-api
    build: docker/.
    image: ryubr:elixir
    working_dir: /var/www
    volumes:
      - .:/var/www/
    environment:
      - MIX_ENV=dev
    entrypoint: [ "/bin/sh" , "/var/www/docker/entrypoint/local.sh" ]
    command: mix phx.server
    # command: iex -S mix phx.server
    ports:
      - 4000:4000
    tty: true
    restart: always
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: heimdallr-db
    environment:
      POSTGRES_DB: heimdallr
      POSTGRES_USER: heimdallr
      POSTGRES_PASSWORD: heimdallr
    ports:
      - 5432:5432
    tty: true
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
